services:
  vpn-bot:
    image: fus1ond/vpn-bot:latest
    container_name: vpn-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - REMNAWAVE_URL=${REMNAWAVE_URL}
      - REMNAWAVE_API_TOKEN=${REMNAWAVE_API_TOKEN}
      - REMNAWAVE_DEFAULT_SQUAD_UUID=${REMNAWAVE_DEFAULT_SQUAD_UUID}
      - DB_PATH=${DB_PATH:-/app/data/bot.db}
      - DONATE_TEXT=${DONATE_TEXT}
    env_file:
      - .env
    networks:
      - vpn-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  vpn-network:
    driver: bridge
